# Generated by Django 5.2.12 on 2026-03-28 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_processing_fees_currency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashpayment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='paypalpayment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='stripepayment',
            options={},
        ),
    ]
