# Generated by Django 5.2.12 on 2026-03-28 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventticketitem',
            options={},
        ),
    ]
