# Generated by Django 4.2.15 on 2024-08-25 23:33

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingevent',
            name='balance_after_apply_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'USD $')], default='USD', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='billingevent',
            name='final_total_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'USD $')], default='USD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='billingevent',
            name='platform_fee_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'USD $')], default='USD', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='billingevent',
            name='processing_fee_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'USD $')], default='USD', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='billingevent',
            name='subtotal_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'USD $')], default='USD', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='partnerbalance',
            name='balance_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'USD $')], default='USD', editable=False, max_length=3),
        ),
    ]
