# Generated by Django 5.2.12 on 2026-03-28 02:12

import djmoney.models.fields
import djmoney.money
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_billingevent_balance_after_apply_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerbalance',
            name='balance',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=djmoney.money.Money('0', 'USD'), max_digits=8),
        ),
    ]
