# Generated by Django 4.2.3 on 2023-09-16 22:06

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poline',
            name='cost_per_item',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=4, default_currency='USD', max_digits=8, null=True),
        ),
    ]
