# Generated by Django 4.2.10 on 2024-02-24 23:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_install_trigram_extension'),
        ('intake', '0004_alter_poline_cost_per_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='dist_has_pricing_col',
            field=models.BooleanField(default=False, help_text='Determines if that column shows on purchase orders'),
        ),
        migrations.AddField(
            model_name='poline',
            name='msrp_on_line',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='poline',
            name='msrp_on_line_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='poline',
            name='pricing',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='DistributorDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('default', models.BooleanField(default=False)),
                ('apply_if_po_starts_with', models.CharField(blank=True, max_length=10, null=True)),
                ('apply_if_pricing_col', models.CharField(blank=True, max_length=10, null=True)),
                ('apply_to_publisher', models.ForeignKey(blank=True, help_text='Only apply if the distributor has various publishers', null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.publisher')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intake.distributor')),
            ],
        ),
        migrations.AddConstraint(
            model_name='distributordiscount',
            constraint=models.UniqueConstraint(condition=models.Q(('default', True)), fields=('distributor', 'default'), name='Only one default per distributor'),
        ),
        migrations.AlterUniqueTogether(
            name='distributordiscount',
            unique_together={('distributor', 'apply_if_po_starts_with'), ('distributor', 'apply_if_pricing_col'), ('distributor', 'apply_to_publisher')},
        ),
    ]
