# Generated by Django 4.2.10 on 2024-03-02 21:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0005_distributor_discounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='date_received',
            field=models.DateField(blank=True, default=datetime.datetime.today, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='date',
            field=models.DateField(help_text='Date Invoiced', null=True),
        ),
    ]
