# Generated by Django 4.2.15 on 2024-08-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0007_poline_distributor_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='separate_invoice_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
