# Generated by Django 4.2.15 on 2024-09-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0009_distributor_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingrule',
            name='use_MAP',
            field=models.BooleanField(default=False, help_text='Uses the MAP, if available, instead of a percent of the MSRP'),
        ),
    ]
