# Generated by Django 4.2.15 on 2024-09-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0010_alter_pricingrule_use_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='distitem',
            name='import_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
