# Generated by Django 4.2.15 on 2024-09-25 22:52

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0011_distitem_import_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='poline',
            name='refunded_quantity',
            field=models.IntegerField(blank=True, default=0, help_text='Any items that were credited'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='amount_credited_charge',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), help_text='Added to amount charged to get actual amount charged', max_digits=8),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='amount_credited_charge_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'USD $')], default='USD', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='amount_credited_subtotal',
            field=djmoney.models.fields.MoneyField(currency_choices=[('USD', 'USD $'), ('GBP', 'GBP £')], decimal_places=2, default=Decimal('0'), help_text='Added to subtotal to get displayed total', max_digits=8),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='amount_credited_subtotal_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'USD $'), ('GBP', 'GBP £')], default='USD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='subtotal',
            field=djmoney.models.fields.MoneyField(blank=True, currency_choices=[('USD', 'USD $'), ('GBP', 'GBP £')], decimal_places=2, help_text='Subtotal after any invoiced credits', max_digits=8, null=True),
        ),
    ]
