# Generated by Django 4.2.16 on 2024-11-29 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0012_poline_refunded_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distitem',
            name='dist_barcode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='poline',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
