# Generated by Django 4.2.16 on 2024-12-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0013_alter_distitem_dist_barcode_alter_poline_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='secondary_sort',
            field=models.CharField(choices=[('name', 'Alphabetical'), ('barcode', 'Barcode')], default='name', max_length=7),
        ),
    ]
