# Generated by Django 4.2.22 on 2025-07-06 21:10

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0014_distributor_secondary_sort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='amount_charged',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, help_text='Final USD amount charged, including tariffs and currency conversions', max_digits=8, null=True),
        ),
    ]
