# Generated by Django 4.2.22 on 2025-07-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0015_alter_purchaseorder_amount_charged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='date',
            field=models.DateField(blank=True, help_text='Date Invoiced', null=True),
        ),
    ]
