# Generated by Django 4.2.27 on 2026-03-05 00:14

from django.db import migrations, models


def forward_func(apps, _):
    inventory_file = apps.get_model("intake", "DistributorInventoryFile")
    for file in inventory_file.objects.all():
        file.save()  # update nice filename


class Migration(migrations.Migration):
    dependencies = [
        ('intake', '0016_alter_purchaseorder_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributorinventoryfile',
            name='filename',
            field=models.CharField(default='Old File', max_length=200),
            preserve_default=False,
        ),
        migrations.RunPython(forward_func, migrations.RunPython.noop),
    ]
