# Generated by Django 4.2.27 on 2026-03-05 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0017_distributorinventoryfile_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributorinventoryfile',
            name='line_count',
            field=models.IntegerField(default=0),
        ),
    ]
