# Generated by Django 4.2.27 on 2026-03-05 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0018_distributorinventoryfile_line_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributorinventoryfile',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='inventory_files', to='intake.distitem'),
        ),
    ]
