# Generated by Django 5.2.13 on 2026-07-12 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0019_distributorinventoryfile_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoInvoiceFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, upload_to='media/')),
                ('filename', models.CharField(max_length=200)),
                ('processing', models.BooleanField(default=False)),
                ('update_date', models.DateTimeField(blank=True)),
                ('processed', models.BooleanField(default=False)),
                ('line_count', models.IntegerField(default=0)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intake.distributor')),
                ('po', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intake.purchaseorder')),
            ],
        ),
    ]
