# Generated by Django 5.2.14 on 2026-07-13 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0020_poinvoicefile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoShipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, max_length=200, null=True)),
                ('carrier', models.CharField(blank=True, max_length=200, null=True)),
                ('carrier_link', models.URLField(blank=True, max_length=500, null=True)),
                ('po', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='intake.purchaseorder')),
            ],
        ),
    ]
