# Generated by Django 5.2.14 on 2026-07-13 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0021_poshipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='last_nshift_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
