# Generated by Django 5.2.14 on 2026-07-19 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0022_purchaseorder_last_nshift_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='poshipment',
            name='nshift_uuid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='PoShipmentLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, help_text='no units')),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('unit_of_measure', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('unit_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sku', models.CharField(blank=True, help_text='article no', max_length=100, null=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='intake.poshipment')),
            ],
        ),
    ]
