# Generated by Django 5.2.15 on 2026-07-26 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0023_poshipment_nshift_uuid_poshipmentline'),
        ('partner', '0004_alter_partner_acct_balance_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerDistAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intake.distributor')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.partner')),
            ],
            options={
                'verbose_name': 'Partner Distributor Authentication',
                'verbose_name_plural': 'Partner Distributor Authentications',
                'unique_together': {('partner', 'distributor')},
            },
        ),
    ]
