# Generated by Django 5.2.15 on 2026-07-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0024_partnerdistauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='distitem',
            name='announced',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='distitem',
            name='expected',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='distitem',
            name='orders_due',
            field=models.DateField(blank=True, null=True),
        ),
    ]
