# Generated by Django 5.2.15 on 2026-07-26 19:31

import django.db.models.deletion
import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0025_distitem_announced_distitem_expected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributorinventoryfile',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='distributorinventoryfile',
            name='filename',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='DistributorInventoryLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msrp_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'USD $')], default='USD', editable=False, max_length=3, null=True)),
                ('msrp', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=8, null=True)),
                ('dist_price_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'USD $')], default='USD', editable=False, max_length=3, null=True)),
                ('dist_price', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=8, null=True)),
                ('orders_due', models.DateField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('dist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intake.distitem')),
                ('inventory_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_lines', to='intake.distributorinventoryfile')),
            ],
        ),
    ]
