# Generated by Django 5.2.15 on 2026-07-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0026_alter_distributorinventoryfile_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributorinventoryline',
            name='announced',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='distributorinventoryline',
            name='expected',
            field=models.DateField(blank=True, null=True),
        ),
    ]
