# Generated by Django 5.2.15 on 2026-07-26 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0027_distributorinventoryline_announced_and_more'),
        ('shop', '0020_alter_customchargeitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.publisher'),
        ),
    ]
