# Generated by Django 5.2.15 on 2026-07-26 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0028_manufacturer_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='distitem',
            name='in_stock',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='distributorinventoryline',
            name='in_stock',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
