# Generated by Django 5.2.15 on 2026-07-26 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0029_distitem_in_stock_distributorinventoryline_in_stock'),
        ('shop', '0020_alter_customchargeitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturerbarcode',
            name='mfc',
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='BarcodePrefix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode_prefix', models.CharField(max_length=7)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.publisher')),
            ],
        ),
        migrations.DeleteModel(
            name='ManufacturerAbbreviation',
        ),
        migrations.DeleteModel(
            name='ManufacturerBarcode',
        ),
    ]
