# Generated by Django 5.2.15 on 2026-07-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0031_distitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='distitem',
            name='product_last_refreshed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
