# Generated by Django 4.2.10 on 2024-03-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box_counter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxinventory',
            name='height_inches',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='boxinventory',
            name='length_inches',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='boxinventory',
            name='width_inches',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
