# Generated by Django 4.2.16 on 2024-11-29 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box_counter', '0002_alter_boxinventory_height_inches_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxinventory',
            name='barcode',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
