# Generated by Django 4.2.27 on 2026-01-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_report', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryreportline',
            name='name_at_time_of_scan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inventoryreportline',
            name='number_at_time_of_scan',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
