# Generated by Django 4.2.27 on 2026-01-01 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_item_in_store_only_price_and_more'),
        ('inventory_report', '0003_inventoryreportline_name_at_time_of_scan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryreportline',
            name='product_at_time_of_scan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product'),
        ),
    ]
