# Generated by Django 4.2.6 on 2023-10-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_cart_invoice_been_printed'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutline',
            name='is_preorder',
            field=models.BooleanField(default=False),
        ),
    ]
