# Generated by Django 4.2.6 on 2023-10-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_checkoutline_is_preorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_tax_rate',
            field=models.FloatField(blank=True, help_text='Percent in decimal form( ex .055)', null=True),
        ),
    ]
