# Generated by Django 4.2.7 on 2024-02-04 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_cart_cart_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='lost_damaged_or_stolen',
            field=models.BooleanField(default=False),
        ),
    ]
