# Generated by Django 4.2.7 on 2024-02-10 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checkout', '0006_cart_lost_damaged_or_stolen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cash_paid',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='discount_code_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='final_digital_tax',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='final_physical_tax',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='final_ship',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='final_tax',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='final_total',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cart',
            name='postage_paid',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_paid',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=19, null=True),
        ),
    ]
