# Generated by Django 4.2.7 on 2024-02-18 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_alter_checkoutline_allow_blank_for_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutline',
            name='qty_before_submit',
        ),
    ]
