# Generated by Django 4.2.10 on 2024-03-02 20:57

import checkout.managers
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_remove_checkoutline_qty_before_submit'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cart',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('open', checkout.managers.OpenCartManager()),
                ('saved', checkout.managers.SavedCartManager()),
                ('submitted', checkout.managers.SubmittedCartManager()),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='broken_down',
            field=models.BooleanField(default=False, help_text='Removed from inventory as it was used for something else'),
        ),
    ]
