# Generated by Django 4.2.16 on 2024-11-24 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0012_alter_cart_amount_refunded_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='merge_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='checkout.cart'),
        ),
    ]
