# Generated by Django 4.2.16 on 2024-12-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0013_cart_merge_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutline',
            name='inventory_at_time_of_submit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
