# Generated by Django 4.2.27 on 2026-01-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0014_checkoutline_inventory_at_time_of_submit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='carrier',
            field=models.CharField(blank=True, choices=[('USPS', 'USPS'), ('UPS', 'UPS'), ('FEDEX', 'FEDEX'), ('DHL', 'DHL')], default=None, max_length=20, null=True, verbose_name='delivery'),
        ),
    ]
