# Generated by Django 5.2.12 on 2026-04-19 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0015_alter_cart_carrier'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='pre_tax_subtotal_includes_shipping',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='billing_address',
            field=models.ForeignKey(blank=True, help_text='No longer used, in favor of always using shipping address', null=True, on_delete=django.db.models.deletion.PROTECT, to='checkout.billingaddress'),
        ),
    ]
