# Generated by Django 4.2.10 on 2024-06-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_info', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='navbar_order',
            field=models.IntegerField(blank=True, help_text='If populated, will appear in navbar, highest first', null=True),
        ),
    ]
