# Generated by Django 4.2.15 on 2024-08-25 23:33

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('game_info', '0003_game_navbar_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='approximate_cost_of_full_force_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'USD $')], default='USD', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='cost_to_start_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'USD $')], default='USD', editable=False, max_length=3, null=True),
        ),
    ]
