# Generated by Django 4.2.15 on 2024-08-25 23:33

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercredit',
            name='balance_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'USD $')], default='USD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='usercreditchange',
            name='change_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'USD $')], default='USD', editable=False, max_length=3),
        ),
    ]
