# Generated by Django 4.2.3 on 2023-09-01 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='allow_extra_preorders',
            field=models.BooleanField(default=False, help_text='If the item is preallocated and backorders are allowed, button will be backorder instead of marking as sold out of pre-orders'),
        ),
    ]
