# Generated by Django 4.2.7 on 2023-12-09 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0002_inventoryitem_allow_extra_preorders'),
        ('intake', '0004_alter_poline_cost_per_item'),

    ]

    operations = [
        migrations.RenameField(
            model_name='inventorylog',
            old_name='quantity',
            new_name='change_quantity'
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='after_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='change_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inv_log',
                                    to='shop.inventoryitem'),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='po',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='intake.purchaseorder'),
        ),
    ]
