# Generated by Django 4.2.7 on 2023-12-30 22:33

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0003_improve_inventorylog'),
    ]

    operations = [
        TrigramExtension(),
    ]
