# Generated by Django 4.2.10 on 2024-03-02 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_install_trigram_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='needs_barcode_printed',
            field=models.BooleanField(default=False),
        ),
    ]
