# Generated by Django 4.2.11 on 2024-07-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_inventoryitem_preallocated_inventory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='no_discount_codes',
            field=models.BooleanField(default=False, help_text='If set, discount codes cannot apply at all'),
        ),
        migrations.DeleteModel(
            name='BackorderRecord',
        ),
    ]
