# Generated by Django 4.2.14 on 2024-08-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_publisher_no_discount_codes_delete_backorderrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='enable_restock_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='low_inventory_alert_threshold',
            field=models.IntegerField(default=0),
        ),
    ]
