# Generated by Django 4.2.22 on 2025-07-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_collection_contents'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_store_early_release_date',
            field=models.DateField(blank=True, help_text='YYYY-MM-DD or MM/DD/YYYY', null=True, verbose_name='Date for early release in store'),
        ),
    ]
