# Generated by Django 4.2.22 on 2025-08-10 16:36

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_product_in_store_early_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='private_notes',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
