# Generated by Django 4.2.22 on 2025-08-30 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_product_private_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='last_stocked_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
