# Generated by Django 4.2.26 on 2025-11-23 02:02

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_inventoryitem_last_stocked_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='in_store_only_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='in_store_only_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'USD $')], default='USD', editable=False, max_length=3, null=True),
        ),
    ]
