# Generated by Django 4.2.27 on 2026-03-05 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_item_in_store_only_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order_cutoff_for_shops_date',
            field=models.DateField(blank=True, help_text='YYYY-MM-DD or MM/DD/YYYY', null=True, verbose_name='Date the store must submit orders by'),
        ),
    ]
