# Generated by Django 5.2.12 on 2026-03-28 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_product_order_cutoff_for_shops_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customchargeitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
        migrations.AlterModelOptions(
            name='madetoorder',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='useditem',
            options={},
        ),
    ]
