# Generated by Django 5.2.15 on 2026-09-16 00:05

import django.db.models.deletion
import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0020_alter_customchargeitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintQueueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_at_adjustment', models.IntegerField(help_text='Quantity in stock when the price change was detected')),
                ('quantity_at_printing', models.IntegerField(blank=True, help_text='Quantity in stock when printing started', null=True)),
                ('old_price_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'USD $')], default='USD', editable=False, max_length=3)),
                ('old_price', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=19)),
                ('new_price_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'USD $')], default='USD', editable=False, max_length=3)),
                ('new_price', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=19)),
                ('printed', models.BooleanField(default=False)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('restickered', models.BooleanField(default=False)),
                ('restickered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.inventoryitem')),
            ],
        ),
    ]
