# Generated by Django 4.2.7 on 2023-12-10 22:15

from django.db import migrations, models

from discount_codes.models import Referrer


def migrate_data_forward(apps, schema_editor):
    print("\n")
    for instance in Referrer.objects.all():
        print("Generating slug for %s" % instance)
        instance.save()  # Will trigger slug update


class Migration(migrations.Migration):
    dependencies = [
        ('discount_codes', '0004_discountcode_in_store_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='referrer',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
        migrations.RunPython(migrate_data_forward, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='referrer',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
