# Generated by Django 4.2.27 on 2026-01-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount_codes', '0006_alter_discountcode_min_cart_for_discount_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='redirect',
            field=models.CharField(blank=True, null=True),
        ),
    ]
