# Generated by Django 4.2.27 on 2026-01-02 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('discount_codes', '0007_discountcode_redirect'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLShortener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='default_shortener', to='sites.site')),
                ('short_site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='short_site', to='sites.site', unique=True)),
            ],
        ),
    ]
