# Generated by Django 5.2.12 on 2026-04-12 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount_codes', '0008_urlshortener'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeusage',
            name='code_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='codeusage',
            name='referrer_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codeusage',
            name='used_link',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='codeusage',
            name='code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='code_usage', to='discount_codes.discountcode'),
        ),
    ]
