# Generated by Django 4.2.22 on 2025-07-14 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0015_product_in_store_early_release_date'),
        ('intake', '0016_alter_purchaseorder_date'),
        ('partner', '0004_alter_partner_acct_balance_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_name', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('resolved', models.BooleanField(default=False, help_text='Has this request been addressed by the distributor by fulfilling or allocating to 0')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intake.distributor')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.partner')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intake.purchaseorder')),
            ],
            options={
                'unique_together': {('partner', 'distributor', 'request_name')},
            },
        ),
        migrations.CreateModel(
            name='DistRequestLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dist_requests.distrequest')),
            ],
            options={
                'unique_together': {('request', 'product')},
            },
        ),
    ]
