# Generated by Django 4.2.29 on 2026-03-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dist_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distrequest',
            name='is_allocation',
            field=models.BooleanField(default=False, help_text='Is this a log of an allocation'),
        ),
    ]
