# Generated by Django 5.2.15 on 2026-07-26 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dist_backorders', '0002_backorderreport_partner'),
        ('partner', '0004_alter_partner_acct_balance_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backorderreport',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.partner'),
        ),
    ]
