# Generated by Django 5.2.15 on 2026-07-29 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dist_backorders', '0003_alter_backorderreport_partner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backorderreportline',
            old_name='unit_price',
            new_name='msrp',
        ),
    ]
