# Generated by Django 4.2.15 on 2024-08-25 23:33

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0003_remove_partner_css_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='acct_balance_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'USD $')], default='USD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='partnertransaction',
            name='balance_after_apply_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'USD $')], default='USD', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='partnertransaction',
            name='transaction_fees_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'USD $')], default='USD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='partnertransaction',
            name='transaction_subtotal_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'USD $')], default='USD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='partnertransaction',
            name='transaction_total_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'USD $')], default='USD', editable=False, max_length=3, null=True),
        ),
    ]
